### PR TITLE
Drop dependency on deprecated `gulp-util`

### LINKED ISSUE #39: Replace deprecated dependency gulp-util
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is one of the most popular packages still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### PR DESCRIPTION
**Pull request by TheDancingCode**
Closes #39

### CODE REVIEW

**Comment by TheDancingCode** [comment]
@adamayres 
Did you get a chance to look at this?

**Comment by TheDancingCode** [comment]
Another friendly reminder.

**Comment by georgegeorge88** [comment]
@shinnn 
Sorry for disturbing, but would it be possible for you to accept this since Adam seems not active in github for half a year. I could see from the history that you have been a contributor and active on this project couple years ago.

It seems gulp-wrap is still used quite a lot.

**Comment by TheDancingCode** [comment]
@adamayres , @shinnn 
Checking in on this again.

**Comment by adamayres** [comment]
Sorry for the radio silence, changes looks good, will merge and bump version.

**Pull request merged**
